dist: xenial

notifications:
  email: false

os:
  - linux
  - osx
  - windows

language: node_js

node_js:
  # - 10.2 # Lock to the version shipped with VSCode 1.31+
  # ... except we need to work around https://github.com/nodejs/node/issues/20498
  # and include the newer version which unbreaks our testing flow
  - 10.5

services:
  - xvfb # Required for VSCode extension tests

before_install:
  - curl https://sh.rustup.rs -sSf -m 60 | sh -s -- --no-modify-path -y -v --default-toolchain stable
  - source $HOME/.cargo/env

script:
  - npm run compile
  - npm run test
  - npm run lint
  - npm run prettier -- --list-different
