dist: xenial

notifications:
  email: false

language: node_js

node_js:
  - 10.2 # Lock to the version shipped with VSCode 1.31+

script:
  - npm run compile
  - npm run lint
  - npm run prettier -- --list-different
